// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bridge-go/pkg/models/shared"
	"net/http"
)

// CreatePaymentLink200ApplicationJSON - Successfully created a payment link
type CreatePaymentLink200ApplicationJSON struct {
	ID  *string `json:"id,omitempty"`
	URL *string `json:"url,omitempty"`
}

type CreatePaymentLinkResponse struct {
	ContentType string
	// Invalid body content
	InvalidBodyContent *shared.InvalidBodyContent
	StatusCode         int
	RawResponse        *http.Response
	// Successfully created a payment link
	CreatePaymentLink200ApplicationJSONObject *CreatePaymentLink200ApplicationJSON
}
