// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bridge-go/pkg/models/shared"
	"net/http"
)

type GetPaymentLinkRequest struct {
	// ID of the payment link to retrieve
	PaymentLinkID string `pathParam:"style=simple,explode=false,name=PaymentLinkID"`
}

type GetPaymentLinkResponse struct {
	ContentType string
	// OK
	PaymentLinkResponse *shared.PaymentLinkResponse
	StatusCode          int
	RawResponse         *http.Response
}
