// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bridge-go/pkg/models/shared"
	"net/http"
)

type RevokePaymentLinkRequest struct {
	// ID of the payment link to be revoked
	PaymentLinkID string `pathParam:"style=simple,explode=false,name=PaymentLinkID"`
}

type RevokePaymentLinkResponse struct {
	ContentType string
	// Invalid body content
	InvalidBodyContent *shared.InvalidBodyContent
	StatusCode         int
	RawResponse        *http.Response
}
