// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Beneficiary struct {
	// The name of the company if the beneficiary is a company.
	CompanyName *string `json:"company_name,omitempty"`
	// The first name of the beneficiary.
	FirstName *string `json:"first_name,omitempty"`
	// The IBAN of the recipient.
	Iban string `json:"iban"`
	// The last name of the beneficiary.
	LastName *string `json:"last_name,omitempty"`
}
