// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// InvalidBodyContent - Invalid body content
type InvalidBodyContent struct {
	DocumentationURL *string `json:"documentation_url,omitempty"`
	Message          *string `json:"message,omitempty"`
	Type             *string `json:"type,omitempty"`
}
