// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PaymentLinksResponse - OK
type PaymentLinksResponse struct {
	Pagination Pagination            `json:"pagination"`
	Resources  []PaymentLinkResponse `json:"resources"`
}
