// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// PaymentLinkResponse - OK
type PaymentLinkResponse struct {
	// The client reference of the payment link.
	ClientReference *string `json:"client_reference,omitempty"`
	// The creation date and time of the payment link.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The expiration date and time of the payment link.
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// The unique identifier of the payment link.
	ID *string `json:"id,omitempty"`
	// The URL of the payment link.
	Link *string `json:"link,omitempty"`
	// The status of the payment link.
	Status *string `json:"status,omitempty"`
	// The transactions associated with the payment link.
	Transactions []Transaction `json:"transactions,omitempty"`
	// The last update date and time of the payment link.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	User      *User      `json:"user,omitempty"`
}
