// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	ClientID     *string `security:"scheme,type=apiKey,subtype=header,name=Client-Id"`
	ClientSecret *string `security:"scheme,type=apiKey,subtype=header,name=Client-Secret"`
}
