// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Transaction struct {
	Amount        float32      `json:"amount"`
	Beneficiary   *Beneficiary `json:"beneficiary,omitempty"`
	Currency      string       `json:"currency"`
	EndToEndID    *string      `json:"end_to_end_id,omitempty"`
	ExecutionDate *time.Time   `json:"execution_date,omitempty"`
	Label         string       `json:"label"`
}
