// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type User struct {
	ExternalReference *string `json:"external_reference,omitempty"`
	FirstName         string  `json:"first_name"`
	LastName          string  `json:"last_name"`
}
